### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by cenchaojun** [TomorrowJW/TPCL_RGBDSOD#1]
Thank you for your great work!
I was wondering if you plan to release your code anytime soon.

**Comment by TomorrowJW** [comment]
感谢关注，看你是中国人，我就中文回复了，八月中旬左右会释放代码和结果到这个仓库，最近不在学校，感谢你的认可和关注，谢谢！

**Comment by cenchaojun** [comment]
> 感谢关注，看你是中国人，我就中文回复了，八月中旬左右会释放代码和结果到这个仓库，最近不在学校，感谢你的认可和关注，谢谢！

好的，好的，期待您的工作😄

**Comment by yuluofeiyu** [comment]
Hello, thank you for your excellent work. If you want to release your code, how long will it take? Thank you

**Comment by TomorrowJW** [comment]
最近正在整理这个工作的代码和标注释，谢谢关注！

**Comment by yuluofeiyu** [comment]
> 最近正在整理这个工作的代码和标注释，谢谢关注！

你好，可以提供一下requirement文件吗？非常感谢！又给博主增加麻烦啦，实在不好意思！

**Comment by Cherxy** [comment]
Hello, thank you for your excellent work again. I was wondering if you plan to release your code anytime soon. Thank you
